# permissions for end users to view maximobundles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maximobundle-viewer-role
rules:
- apiGroups:
  - manage.example.com
  resources:
  - maximobundles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manage.example.com
  resources:
  - maximobundles/status
  verbs:
  - get
