# permissions for end users to edit maximobundles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maximobundle-editor-role
rules:
- apiGroups:
  - manage.example.com
  resources:
  - maximobundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manage.example.com
  resources:
  - maximobundles/status
  verbs:
  - get
